org: greet
service: authService

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    CLIENT_ID: ${ssm:/CLIENT_ID}


  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:us-east-1:010526250202:table/User_Table

functions:
  signUp:
    handler: handlers/signUp.signUp
    events:
      - http:
          path: signup
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: User_Table
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
